### PR TITLE
Laravel 11.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 11.x.

**Before merging**, you need to:

- Checkout the `l11-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: The latest version of Laravel has a dependency for `phpunit/phpunit` of `^10.5`. If you would like to also upgrade your tests, you may run the [PHPUnit 10 Shift](https://laravelshift.com/upgrade-phpunit-10) for free.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/unobserve.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "monooso/unobserve": "dev-l11-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by mbardelmeijer** [comment]
@monooso would you mind taking a look at this PR to support Laravel 11? Thanks! 🙏

**Review by monooso — APPROVED** [review]

**Comment by monooso** [comment]
@mbardelmeijer Looks like I need to pull down the code, and make some updates locally. I'll try to get to it this week, but as I don't have even PHP installed at present it's a bit more hassle than it first appears.

**Comment by monooso** [comment]
@mbardelmeijer @laravel-shift This ended up being a bit more work than expected, so I started from scratch on a separate branch.

Everything is now merged to `main` and [I've released a new version](https://packagist.org/packages/monooso/unobserve#v6.0.0), compatible with Laravel 11.

**Comment by mbardelmeijer** [comment]
> @mbardelmeijer @laravel-shift This ended up being a bit more work than expected, so I started from scratch on a separate branch.
> 
> Everything is now merged to `main` and [I've released a new version](https://packagist.org/packages/monooso/unobserve#v6.0.0), compatible with Laravel 11.

Awesome, thanks! :shipit:

**Pull request closed without merging**
