### PR TITLE
Add Laravel 7 support

### PR DESCRIPTION
**Pull request by mikemand**
I didn't realize the `composer.lock` was included. I can revert that file if you want me to.

### CODE REVIEW

**Comment by monooso** [comment]
@mikemand Looks like the Travis tests are failing for PHP 7.2, possibly because Laravel 7 requires `>= 7.2.5`. I'll figure out what's going on this week.

**Comment by mikemand** [comment]
Hi @monooso,

It's because I added the ability to use PHPUnit 9. If we remove that, the tests are fine. PHPUnit 9 is PHP >=7.3.

I can remove PHPUnit 9 if you want me to.

**Comment by denisdulici** [comment]
@monooso any chance to look at this?

**Comment by wilburpowery** [comment]
Added #6 without noticing you already had this PR opened 🤭

If anything, all tests are passing there.

**Comment by monooso** [comment]
@mikemand Laravel 7 is now available on the `2.x` branch. Thanks for the nudge.

**Pull request closed without merging**
