### PR TITLE
Laravel 9.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 9.x.

**Before merging**, you need to:

- Checkout the `l9-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/unobserve.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "monooso/unobserve": "dev-l9-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by denisdulici** [comment]
@monooso Any update on this?

**Comment by monooso** [comment]
@laravel-shift Can you update the `composer.lock` file, please? I don't even have PHP installed any more.

**Comment by monooso** [comment]
@denisdulici See above.

**Comment by spinzar** [comment]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires laravel/framework ^9.9 -> satisfiable by laravel/framework[v9.9.0].
    - monooso/unobserve 5.x-dev requires illuminate/support ^8.22.1 -> satisfiable by illuminate/support[v8.22.1, ..., v8.83.9]. 
    - Only one of these can be installed: illuminate/support[v5.0.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.9, v9.0.0, ..., v9.9.0], laravel/framework[v9.9.0]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
    - Root composer.json requires monooso/unobserve 5.x-dev -> satisfiable by monooso/unobserve[5.x-dev].

**Comment by monooso** [comment]
Closed in favour of #22.

**Pull request closed without merging**
